# Generated by Django 3.1.6 on 2021-02-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfRooms', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
